# Site settings
title: Eric Mittelhammer
email: your-email@yourdomain.com
description: "Software Guy Doing Software Things"
url: "http://ericmittelhammer.com"
twitter_username: emittelhammer
github_username:  ericmittelhammer

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
